export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const RESET_INGREDIENTS = 'RESET_INGREDIENTS';
export const INIT_INGREDIENTS = 'INIT_INGREDIENTS';

export const SEND_ORDER = 'SEND_ORDER';
export const START_SEND_ORDER = 'START_SEND_ORDER';
export const ORDER_SUCCESS = 'ORDER_SUCCESS';
export const ORDER_FAIL = 'ORDER_FAIL';

export const INIT_ORDERS_LIST = 'INIT_ORDERS_LIST';
export const FETCH_ORDERS_LIST_SUCCESS = 'FETCH_ORDERS_LIST_SUCCESS';
export const FETCH_ORDERS_LIST_FAIL = 'FETCH_ORDERS_LIST_FAIL';
export const RESET_ORDERS_LIST = 'RESET_ORDERS_LIST';

export const SIGN_UP_START = 'SIGN_UP_START';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';
export const SIGN_UP_RESET = 'SIGN_UP_RESET';

export const SIGN_IN_START = 'SIGN_IN_START';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';

export const LOGOUT = 'LOGOUT';

export const PAGE_LOADING = 'PAGE_LOADING';
export const PAGE_LOADED = 'PAGE_LOADED';