export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const RESET_INGREDIENTS = 'RESET_INGREDIENTS';
export const INIT_INGREDIENTS = 'INIT_INGREDIENTS';

export const SEND_ORDER = 'SEND_ORDER';
export const START_SEND_ORDER = 'START_SEND_ORDER';
export const ORDER_SUCCESS = 'ORDER_SUCCESS';
export const ORDER_FAIL = 'ORDER_FAIL';

export const INIT_ORDERS_LIST = 'INIT_ORDERS_LIST';
export const FETCH_ORDERS_LIST_SUCCESS = 'FETCH_ORDERS_LIST_SUCCESS';
export const FETCH_ORDERS_LIST_FAIL = 'FETCH_ORDERS_LIST_FAIL';